_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "6": 4.50.2
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
        visualize:
            delta_curve/delta_sparsity_count:
                panel_config:
                    fieldSettings:
                        lineKey: lineKey
                        lineVal: lineVal
                        step: step
                    panelDefId: wandb/lineseries/v0
                    stringSettings:
                        title: delta_sparsity_count curve
                        xname: iteration
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: delta_curve/delta_sparsity_count_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            delta_curve/delta_sparsity_percentage:
                panel_config:
                    fieldSettings:
                        lineKey: lineKey
                        lineVal: lineVal
                        step: step
                    panelDefId: wandb/lineseries/v0
                    stringSettings:
                        title: delta_sparsity_percentage curve
                        xname: iteration
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: delta_curve/delta_sparsity_percentage_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            delta_curve/delta_sparsity_ratio_feature_acts:
                panel_config:
                    fieldSettings:
                        lineKey: lineKey
                        lineVal: lineVal
                        step: step
                    panelDefId: wandb/lineseries/v0
                    stringSettings:
                        title: delta_sparsity_ratio_feature_acts curve
                        xname: iteration
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: delta_curve/delta_sparsity_ratio_feature_acts_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            loss_curve/l1_loss:
                panel_config:
                    fieldSettings:
                        lineKey: lineKey
                        lineVal: lineVal
                        step: step
                    panelDefId: wandb/lineseries/v0
                    stringSettings:
                        title: l1_loss curve
                        xname: iteration
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: loss_curve/l1_loss_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            loss_curve/nll_loss:
                panel_config:
                    fieldSettings:
                        lineKey: lineKey
                        lineVal: lineVal
                        step: step
                    panelDefId: wandb/lineseries/v0
                    stringSettings:
                        title: nll_loss curve
                        xname: iteration
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: loss_curve/nll_loss_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            loss_curve/total_loss:
                panel_config:
                    fieldSettings:
                        lineKey: lineKey
                        lineVal: lineVal
                        step: step
                    panelDefId: wandb/lineseries/v0
                    stringSettings:
                        title: total_loss curve
                        xname: iteration
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: loss_curve/total_loss_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
attn_module_tmp:
    value: model.layers.{}.self_attn
clamp_norm_factor:
    value: 4
context_template_length_params:
    value:
        - - 5
          - 10
        - - 10
          - 10
fact_token:
    value: subject_last
kl_factor:
    value: 0.0625
layer_module_tmp:
    value: model.layers.{}
layers:
    value:
        - 4
lm_head_module:
    value: lm_head
ln_f_module:
    value: model.norm
mlp_module_tmp:
    value: model.layers.{}.mlp
mom2_adjustment:
    value: true
mom2_dataset:
    value: wikipedia
mom2_dtype:
    value: float32
mom2_n_samples:
    value: 100000
rewrite_module_tmp:
    value: model.layers.{}.mlp.down_proj
v_alpha:
    value: 1e-06
v_loss_layer:
    value: 23
v_lr:
    value: 0.5
v_num_grad_steps:
    value: 2
v_weight_decay:
    value: 0.5
